Repository Voirsy/voirsy-front-end, pull requests merged in 2022-01, with the labels that each got.

#34 Fixing filters translations and the login button
  src/components/Filters/index.tsx
  src/components/Header/header.styles.ts
  src/components/Header/index.tsx
  src/server/db.json
Labels: bug, enhancement, refactoring

#33 Creating a reservation view
  public/locales/en-us/salon.json
  public/locales/pl-pl/salon.json
  src/config/locales.ts
  src/endpoints/salon.ts
  src/helpers/util.ts
  src/server/routes.json
  src/store/api/salon/salon.ts
  src/store/api/salon/salon.types.ts
  src/templates/Main/index.tsx
  src/views/Root/index.tsx
  src/views/Salon/Components/Reservation/index.tsx
  src/views/Salon/Components/Reservation/reservation.styled.ts
  src/views/Salon/Components/ServiceCard/index.tsx
  src/views/Salon/index.tsx
Labels: enhancement, refactoring

#38 Fix: general improvements
  package-lock.json
  public/locales/pl-pl/common.json
  src/components/Header/index.tsx
  src/views/Home/index.tsx
  src/views/Salon/Components/NoContent/noContent.styled.ts
Labels: bug, refactoring

#39 fix: incorrect destructuring
  src/components/Header/index.tsx
Labels: bug

#40 fix: general
  public/locales/en-us/admin.json
  public/locales/en-us/common.json
  public/locales/en-us/validation.json
  public/locales/pl-pl/admin.json
  public/locales/pl-pl/common.json
  public/locales/pl-pl/validation.json
  src/components/AdminPanelNavigation/adminPanelNavigation.list.tsx
  src/components/AdminPanelNavigation/index.tsx
  src/store/api/salon/salon.ts
  src/views/Admin/CreateSalonForm/index.tsx
  src/views/Admin/Details/index.tsx
Labels: bug, enhancement, refactoring

#41 CI: add unit and e2e testing into gh action
  .github/workflows/deploy.yml
  .github/workflows/main.yml
  cypress.json
  cypress/integration/main_view.spec.ts
  cypress/plugins/index.js
  cypress/support/commands.js
  cypress/support/index.js
  cypress/videos/main_view.spec.ts.mp4
  package-lock.json
  package.json
  src/components/Filters/index.tsx
  src/views/Home/index.tsx
  src/views/Login/Components/LoginForm/index.tsx
  src/views/Login/Components/LoginForm/loginForm.spec.tsx
Labels: DevOps
